// Les 5 espèces de base de la Serre 1 (tempérée).
// Données issues du GDD §04 — Générateurs.
// growTime en secondes · baseRevenue et seedCost en €.
export const PLANTS = {
  daisy: {
    id: 'daisy',
    name: 'Marguerite commune',
    icon: '🌼',
    biome: 'temperate',
    rarity: 1,
    growTime: 120,        // 2 min
    baseRevenue: 5,
    seedCost: 1,
    color: '#f5e6a8',
    petalColor: '#ffffff',
    height: 0.5,
    description: 'Première plante débloquée. Pousse vite, vend peu. Le tutoriel en pratique.',
    unlockedFromStart: true,
  },
  tulip: {
    id: 'tulip',
    name: 'Tulipe hollandaise',
    icon: '🌷',
    biome: 'temperate',
    rarity: 2,
    growTime: 480,        // 8 min
    baseRevenue: 22,
    seedCost: 6,
    color: '#e07a92',
    petalColor: '#e85a82',
    height: 0.7,
    description: 'Classique du marché floral. Demande fluctuante selon la saison.',
    unlockCost: 50,
  },
  rose: {
    id: 'rose',
    name: 'Rose de Damas',
    icon: '🌹',
    biome: 'temperate',
    rarity: 3,
    growTime: 1500,       // 25 min
    baseRevenue: 85,
    seedCost: 22,
    color: '#c63950',
    petalColor: '#d63b5a',
    height: 0.9,
    description: 'Très prisée pour la parfumerie. Prix élevé, pousse lente.',
    unlockCost: 500,
  },
  lavender: {
    id: 'lavender',
    name: 'Lavande de Provence',
    icon: '🪻',
    biome: 'temperate',
    rarity: 2,
    growTime: 900,        // 15 min
    baseRevenue: 45,
    seedCost: 14,
    color: '#9d7ec8',
    petalColor: '#a87ec4',
    height: 0.8,
    description: 'Résistante, populaire. Bonus de rendement en été.',
    unlockCost: 200,
  },
  peony: {
    id: 'peony',
    name: 'Pivoine impériale',
    icon: '🌺',
    biome: 'temperate',
    rarity: 4,
    growTime: 3600,       // 60 min
    baseRevenue: 280,
    seedCost: 80,
    color: '#e8a4b8',
    petalColor: '#f0b4c4',
    height: 1.1,
    description: 'Fleur haut de gamme. Marché de luxe uniquement.',
    unlockCost: 5000,
  },

  // ─── Espèces tropicales (Indonésie) ─────────────────────
  // Découvrables via expédition. Plantables dans la Serre Tropicale (Prompt 8).
  orchid: {
    id: 'orchid',
    name: 'Orchidée de Sumatra',
    scientificName: 'Phalaenopsis sumatrana',
    icon: '🌸',
    biome: 'tropical',
    rarity: 5,
    growTime: 2700,
    baseRevenue: 350,
    seedCost: 60,
    color: '#d4a4c8',
    petalColor: '#f5c8e0',
    height: 0.7,
    description: 'Exotique et fragile. Nécessite hygrométrie. Très rentable.',
    poetic: 'Fleur de la jungle profonde, elle ne s\'épanouit qu\'en silence.',
  },
  hibiscus: {
    id: 'hibiscus',
    name: 'Hibiscus tropical',
    scientificName: 'Hibiscus rosa-sinensis',
    icon: '🌺',
    biome: 'tropical',
    rarity: 4,
    growTime: 1800,
    baseRevenue: 180,
    seedCost: 35,
    color: '#e85a3a',
    petalColor: '#ff7050',
    height: 0.9,
    description: 'Fleur écarlate des îles. Chaque pétale dure une journée.',
    poetic: 'Brève comme un soleil couchant — flamboyante avant d\'éclore demain.',
  },
  ylang: {
    id: 'ylang',
    name: 'Ylang-Ylang',
    scientificName: 'Cananga odorata',
    icon: '🌼',
    biome: 'tropical',
    rarity: 5,
    growTime: 3600,
    baseRevenue: 500,
    seedCost: 90,
    color: '#f5e070',
    petalColor: '#fff0a0',
    height: 1.2,
    description: 'Source du parfum d\'orient. Pousse lente, valeur extrême.',
    poetic: 'Sa fragrance traverse l\'océan avant que la fleur ne s\'effleure.',
  },
  lotus: {
    id: 'lotus',
    name: 'Lotus sacré',
    scientificName: 'Nelumbo nucifera',
    icon: '🪷',
    biome: 'tropical',
    rarity: 5,
    growTime: 3000,
    baseRevenue: 420,
    seedCost: 75,
    color: '#f5c8d8',
    petalColor: '#ffd8e0',
    height: 0.8,
    description: 'Fleur de la sérénité. Aussi prisée pour la cuisine.',
    poetic: 'Né de la boue, il s\'élève pur — leçon offerte aux jardiniers patients.',
  },

  // ─── Espèces désertiques (Maroc) ────────────────────────
  desert_rose: {
    id: 'desert_rose',
    name: 'Rose du désert',
    scientificName: 'Adenium obesum',
    icon: '🥀',
    biome: 'arid',
    rarity: 4,
    growTime: 2400,
    baseRevenue: 320,
    seedCost: 55,
    color: '#e85070',
    petalColor: '#f57090',
    height: 0.7,
    description: 'Tronc renflé, fleurs éclatantes. Stocke l\'eau pendant des mois.',
    poetic: 'Dans le silence du désert, elle fleurit pour personne — et c\'est sa beauté.',
  },
  saffron: {
    id: 'saffron',
    name: 'Crocus à safran',
    scientificName: 'Crocus sativus',
    icon: '🌷',
    biome: 'arid',
    rarity: 5,
    growTime: 3000,
    baseRevenue: 600,
    seedCost: 100,
    color: '#c870e8',
    petalColor: '#d890f0',
    height: 0.4,
    description: 'L\'or rouge — épice la plus chère au monde.',
    poetic: 'Trois stigmates par fleur, des centaines pour un gramme : la patience valorisée.',
  },
  cactus: {
    id: 'cactus',
    name: 'Cactus géant',
    scientificName: 'Carnegiea gigantea',
    icon: '🌵',
    biome: 'arid',
    rarity: 6,
    growTime: 5400,
    baseRevenue: 800,
    seedCost: 150,
    color: '#5a8a4a',
    petalColor: '#f5f0d8',
    height: 1.4,
    description: 'Sentinelle du désert. Fleurit une nuit par an mais quel spectacle.',
    poetic: 'Mille ans pour s\'élever, une nuit pour fleurir.',
  },

  // ─── Espèces arctiques (Islande) ────────────────────────
  edelweiss: {
    id: 'edelweiss',
    name: 'Edelweiss arctique',
    scientificName: 'Leontopodium alpinum borealis',
    icon: '❄️',
    biome: 'arctic',
    rarity: 6,
    growTime: 3000,
    baseRevenue: 700,
    seedCost: 120,
    color: '#f0f8ff',
    petalColor: '#ffffff',
    height: 0.5,
    description: 'Étoile blanche des sommets glacés. Survit là où rien d\'autre ne pousse.',
    poetic: 'Pure comme la neige, vivace comme la pierre.',
  },
  glow_moss: {
    id: 'glow_moss',
    name: 'Mousse lumineuse',
    scientificName: 'Lichen luminescens',
    icon: '🌿',
    biome: 'arctic',
    rarity: 5,
    growTime: 1800,
    baseRevenue: 400,
    seedCost: 70,
    color: '#7eecca',
    petalColor: '#a0f5d4',
    height: 0.3,
    description: 'Bioluminescente la nuit. Très demandée pour la décoration.',
    poetic: 'Quand tombe la nuit polaire, elle devient le seul soleil.',
  },
  aurora_lily: {
    id: 'aurora_lily',
    name: 'Lys d\'aurore',
    scientificName: 'Borealis lilium',
    icon: '🪻',
    biome: 'arctic',
    rarity: 7,
    growTime: 4800,
    baseRevenue: 1500,
    seedCost: 250,
    color: '#88c4ff',
    petalColor: '#c0e0ff',
    height: 1.0,
    description: 'Pétales irisés qui changent avec la lumière. Légendaire.',
    poetic: 'Elle capture l\'aurore boréale dans chaque pétale — un don du Nord.',
  },
};

export const PLANT_LIST = Object.values(PLANTS);
